default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
  run_tests(workspace: "TuneSearch.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "TuneSearch")
  end
end
