project 'TuneSearch.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TuneSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuneSearch
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'BasicCleanArch', '~> 5'

  target 'TuneSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
