name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: gem install xcpretty
      - run: |
          cd TuneSearch
          set -o pipefail && xcodebuild test -enableCodeCoverage YES \
          -workspace TuneSearch.xcworkspace -scheme TuneSearch \
          -sdk iphonesimulator \ 
          -destination 'platform=iOS Simulator,name=iPhone 11' \ 
          ONLY_ACTIVE_ARCH=NO | xcpretty